Improve documentation a bit
oscar-system/GAP.jl pull request #929
Opened 2023-08-21 07:49 UTC by fingolfin

2023-08-21 09:47 UTC, ThomasBreuer commented on docs/src/other.md
> +- Access record components via [`getproperty`](@ref) and [`!etproperty!`](@ref)
setproperty!

2023-08-21 11:51 UTC, ThomasBreuer requested changes
just a typo in a cross-reference

2023-08-22 07:46 UTC, fingolfin commented on docs/src/other.md
> +- Access record components via [`getproperty`](@ref) and [`!etproperty!`](@ref)
```suggestion
- Access record components via [`getproperty`](@ref) and [`setproperty!`](@ref)
```

2023-08-22 08:52 UTC, fingolfin commented
Fixed

2023-08-25 13:05 UTC, ThomasBreuer approved these changes

2023-08-25 13:05 UTC, merged